# Generated by Django 5.1.2 on 2024-10-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_account_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_number',
            new_name='transaction_id',
        ),
    ]
