# Generated by Django 5.1.2 on 2024-11-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_cover_picture_profile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('agent', 'Agent')], default='Personal', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('all', 'Bkash, Nagad, Rocket')], default='Bkash', max_length=10),
        ),
    ]
