# Generated by Django 5.1.2 on 2024-12-04 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=6, unique=True),
        ),
    ]
