# Generated by Django 5.1.2 on 2024-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_passwordreset_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='uuid',
            field=models.CharField(default='6074', max_length=6, unique=True),
        ),
    ]
