# Generated by Django 5.1.2 on 2024-12-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_passwordreset_uuid_post_postlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='author',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'profile')},
        ),
    ]
