# Generated by Django 5.1.2 on 2024-12-26 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_rename_author_postlike_profile_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='activate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
