# Generated by Django 5.1.2 on 2025-01-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_accounts_activate_date_and_more'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='course_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'),
        ),
    ]
